project:
  type: book

book:
  title: "Regression Notes"
  author: "Kelly Ramsay"
  date: last-modified
  chapters:
    - index.qmd
    - part: "Review material"
      chapters:
        - Unit_1_1.qmd
        - Unit_1_2.qmd
        - Unit_1_3.qmd
        - Unit_1_4.qmd

format:
  html:
    theme: cosmo
    toc: true
    number-sections: true
    code-fold: false
    smooth-scroll: false
    anchor-sections: false

editor: source
