<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>2&nbsp; Review of introductory statistics – Regression Notes</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./Unit_1_3.html" rel="next">
<link href="./Unit_1_1.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-ed7344add5f1663e434276306a2aa159.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./Unit_1_1.html">Review material</a></li><li class="breadcrumb-item"><a href="./Unit_1_2.html"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Review of introductory statistics</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Regression Notes</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Review material</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Unit_1_1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Review of random variables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Unit_1_2.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Review of introductory statistics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Unit_1_3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Review of matrices and linear algebra</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Unit_1_4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Review Random Vectors</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Glossary.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Glossary</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#basic-premise-of-statistics" id="toc-basic-premise-of-statistics" class="nav-link active" data-scroll-target="#basic-premise-of-statistics"><span class="header-section-number">2.1</span> Basic premise of statistics</a></li>
  <li><a href="#hypothesis-tests" id="toc-hypothesis-tests" class="nav-link" data-scroll-target="#hypothesis-tests"><span class="header-section-number">2.2</span> Hypothesis tests</a></li>
  <li><a href="#check-your-understanding" id="toc-check-your-understanding" class="nav-link" data-scroll-target="#check-your-understanding"><span class="header-section-number">2.3</span> Check Your Understanding</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./Unit_1_1.html">Review material</a></li><li class="breadcrumb-item"><a href="./Unit_1_2.html"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Review of introductory statistics</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Review of introductory statistics</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>This section reviews the core machinery of introductory statistics — confidence intervals and hypothesis tests — through two fully worked examples in R. These are the tools we will lean on throughout the course: once we build a regression estimator, we will want to attach a confidence interval to it and test whether a coefficient is really nonzero, and both of those tasks use exactly the logic developed here.</p>
<p>The followings are some concepts that you have learned from prerequisites, and/or we have reviewed in the last two lectures.</p>
<ul>
<li>Sample vs.&nbsp;Population</li>
<li>Observation vs.&nbsp;Random variable</li>
<li>Statistic vs.&nbsp;Parameter</li>
<li>Estimate vs.&nbsp;Estimator</li>
<li>Estimator is a random variable and estimate is a number calculated from data</li>
<li>Mean and variance of random variable</li>
<li>Relationships between Normal, <span class="math inline">\(t\)</span> , <span class="math inline">\(\chi^2\)</span>, <span class="math inline">\(F\)</span> etc.</li>
</ul>
<section id="basic-premise-of-statistics" class="level2" data-number="2.1">
<h2 data-number="2.1" data-anchor-id="basic-premise-of-statistics"><span class="header-section-number">2.1</span> Basic premise of statistics</h2>
<p>The whole purpose of statistics is to learn something about a population using only a sample of units from that population. A <strong>sample</strong> is a smaller, typically randomly selected, subset of a population. A <strong>population</strong> is a collection of units which we would like to know something about. For example, we may collect a sample of hamburgers from McDonald’s if we want to learn something about the population of McDonald’s hamburgers.</p>
<p>In general, at least for this course, we assume that we have access to a sample of units from a given population. Furthermore, we assume that that sample is a <strong>random sample</strong>. Specifically, we assume that these units in the sample are realizations of random variables. In addition, we also assume that these random variables are mutually independent. For example, we could assume that our sample <span class="math inline">\(X_1,\ldots,X_n\)</span> is Normally distributed with some fixed mean <span class="math inline">\(\mu\)</span> and fixed variance <span class="math inline">\(\sigma^2\)</span>. In this case, <span class="math inline">\(\mu\)</span> and <span class="math inline">\(\sigma^2\)</span> are unknown <strong>parameters</strong> of the population. A parameter of a population is some quantity that is a function of the distribution of our given sample. For instance, <span class="math inline">\({\textrm{E}}\left[X_i\right]=\mu\)</span>. Generally, we are concerned with unknown population parameters, which are parts of the distribution that are unknown, and can only ever be estimated. For example, we may know our data is normal, but not know the mean parameter. In that case, we need to use an <strong>estimate</strong> of the parameter. We use a function of the data, typically called the estimator, say <span class="math inline">\(T\)</span>, which produces the estimate, given by <span class="math inline">\(T\)</span> computed at the sample we observed: <span class="math inline">\(T(X_1,\ldots,X_n)\)</span>.</p>
<p>For example, to estimate <span class="math inline">\(\mu\)</span>, we typically use the sample mean. Here, the estimate is given by <span class="math inline">\(\bar X=\sum_{i=1}^nX_i/n\)</span>. To be specific, the estimate is the value of <span class="math inline">\(\bar X\)</span> and the estimator <span class="math inline">\(T\)</span> is the function that maps <span class="math inline">\(n\)</span> real numbers to their mean. In general, estimates are used to give our `best guess’ at population parameters.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Intuition: estimator vs. estimate">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Intuition: estimator vs.&nbsp;estimate
</div>
</div>
<div class="callout-body-container callout-body">
<p>This distinction trips a lot of people up, so here’s a concrete way to keep it straight: the <strong>estimator</strong> is a <em>recipe</em> (a formula, like “add up the numbers and divide by how many there are”), while the <strong>estimate</strong> is the <em>dish</em> you get out once you actually plug in ingredients. <span class="math inline">\(\bar X=\sum_{i=1}^n X_i/n\)</span> is the recipe — it works no matter what sample you feed it, which is exactly why it’s a random variable (feed it a different sample, get a different number out). If your actual data happens to be <span class="math inline">\(2,4,6\)</span>, the estimate is the specific number <span class="math inline">\(4\)</span>. Every time you collect a new sample, the estimator stays the same rule, but the estimate it spits out will typically change.</p>
</div>
</div>
<p>Recall from the previous section that our estimate of a parameter is only that, an estimate. In other words, it is not exactly equal to the population parameter. For instance, if we drew a different sample our estimate would change. A confidence interval is used to acknowledge this phenomenon in the reporting of our statistics. Its used to give a range of estimates that we might have obtained from any “regular” sample we might observe. It is ultimately used to quantify the error (sometimes called uncertainty) in our estimate.</p>
<p>Confidence intervals consist of a level, usually denoted by <span class="math inline">\((1-\alpha)100\%\)</span> and two end points. For example, you have learned confidence intervals for the population mean. When we say <span class="math inline">\((-1,1)\)</span> is <span class="math inline">\(95\%\)</span> confidence interval for the population mean, what does this mean? Colloquially, it means that we expect the sample mean to be somewhere within <span class="math inline">\((-1,1)\)</span> with high confidence. Note that confidence intervals are computed from the data, which means also that for each new sample, we would get a different confidence interval. However, the population parameter never changes. Therefore, the interval is what is varying from sample to sample. This impacts the interpretation of a confidence interval.</p>
<p>Continuing our example, we have that the interval <span class="math inline">\((-1,1)\)</span> can be interpreted as: “if we drew many more samples, 95% of the <strong>intervals</strong> will contain the population parameter.” We <strong>do not</strong> say that the parameter has a 95% chance of falling in (-1,1), since the parameter is not random, the interval end points are.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Intuition: it's the interval that's random, not the parameter">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Intuition: it’s the interval that’s random, not the parameter
</div>
</div>
<div class="callout-body-container callout-body">
<p>This is the single most commonly misstated idea in intro statistics, so it’s worth slowing down on. Imagine the true (unknown, fixed) population mean is <span class="math inline">\(\mu=170\)</span>cm. You draw a sample and compute a 95% CI of <span class="math inline">\((168,172)\)</span> — it happens to contain <span class="math inline">\(170\)</span>. A colleague draws a <em>different</em> sample from the same population and gets <span class="math inline">\((171,174)\)</span> — it happens to <em>miss</em> <span class="math inline">\(170\)</span>. The number <span class="math inline">\(170\)</span> never moved; it’s a fixed constant. What moved was the <em>interval</em>, because it was built from random data. “95% confidence” describes the <em>procedure</em>: if you repeated this sampling-and-interval-building process over and over, about 95% of the resulting intervals would happen to capture the true <span class="math inline">\(\mu\)</span>. It does <strong>not</strong> mean “there’s a 95% chance <span class="math inline">\(\mu\)</span> is in this one particular interval you already computed” — <span class="math inline">\(\mu\)</span> either is or isn’t in it; there’s no probability left once the interval is drawn.</p>
</div>
</div>
<div style="text-align:center; margin: 1.5em 0;">
<svg viewbox="0 0 520 200" width="100%" style="max-width:480px;" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="A vertical dashed line marks the fixed true population mean. Around it, several horizontal confidence intervals from different hypothetical samples are drawn; most cross the true mean line but one, shown in red, misses it, illustrating that roughly 95 percent of such intervals would contain the true mean.">
<line x1="260" y1="10" x2="260" y2="190" stroke="#c0392b" stroke-width="1.5" stroke-dasharray="5,4"></line> <text x="260" y="198" font-size="13" text-anchor="middle" fill="#c0392b">true μ (fixed, unknown)</text> <g stroke-width="4" fill="none"> <line x1="190" y1="30" x2="310" y2="30" stroke="#2e86c1"></line> <line x1="215" y1="55" x2="330" y2="55" stroke="#2e86c1"></line> <line x1="180" y1="80" x2="290" y2="80" stroke="#2e86c1"></line> <line x1="230" y1="105" x2="340" y2="105" stroke="#2e86c1"></line> <line x1="270" y1="130" x2="150" y2="130" stroke="#c0392b"></line> <line x1="200" y1="155" x2="320" y2="155" stroke="#2e86c1"></line> </g> <text x="60" y="134" font-size="12" text-anchor="start" fill="#c0392b">misses μ</text>
</svg>
</div>
<p>For example, we have the formula for a confidence interval for the population mean is given by: <span class="math inline">\(\bar X\pm 1.96\hat\sigma\)</span>. Notice that it is based only on the data. Therefore, it will change if we drew a new sample.</p>
<div class="callout callout-style-default callout-important callout-titled" title="Numerical Example 2.1: computing a confidence interval by hand">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Numerical Example 2.1: computing a confidence interval by hand
</div>
</div>
<div class="callout-body-container callout-body">
<p>Suppose we take a random sample of <span class="math inline">\(n=25\)</span> packages from a shipping company and weigh each one. We find a sample mean weight of <span class="math inline">\(\bar X=52\)</span> kg. Assume the population standard deviation is known to be <span class="math inline">\(\sigma=10\)</span> kg (in practice we’d rarely know <span class="math inline">\(\sigma\)</span> exactly, but this keeps the arithmetic simple — we’ll switch to the estimated <span class="math inline">\(\hat\sigma\)</span> and a <span class="math inline">\(t\)</span>-distribution once we get to the worked <span class="math inline">\(R\)</span> examples below). Construct a 95% confidence interval for the true mean package weight <span class="math inline">\(\mu\)</span>.</p>
<p><em>Solution.</em> The standard error of <span class="math inline">\(\bar X\)</span> is <span class="math display">\[\textrm{SE}(\bar X)=\frac{\sigma}{\sqrt n}=\frac{10}{\sqrt{25}}=\frac{10}{5}=2.\]</span> For a 95% confidence level, the relevant multiplier is <span class="math inline">\(1.96\)</span> (this comes from the standard Normal distribution: 95% of its probability lies within <span class="math inline">\(\pm1.96\)</span> of 0). So the margin of error is <span class="math display">\[1.96\times \textrm{SE}(\bar X)=1.96\times 2=3.92.\]</span> The confidence interval is therefore <span class="math display">\[\bar X\pm 3.92 = 52\pm 3.92 = (48.08,\ 55.92).\]</span> <strong>Interpretation:</strong> we are 95% confident that the true mean package weight <span class="math inline">\(\mu\)</span> lies between 48.08 kg and 55.92 kg. More precisely, if we repeated this sampling process many times, about 95% of the intervals we’d construct this way would contain the true <span class="math inline">\(\mu\)</span> — the number <span class="math inline">\(52\)</span> that we plugged in is just one sample’s estimate, and would be different for a different sample of 25 packages.</p>
</div>
</div>
<p>To summarize this section, a confidence interval is used to quantify the uncertainty in our reported estimates. By uncertainty, we specifically mean the uncertainty resulting from the fact that we have only a sample of the population, and our estimate varies depending on the sample.</p>
</section>
<section id="hypothesis-tests" class="level2" data-number="2.2">
<h2 data-number="2.2" data-anchor-id="hypothesis-tests"><span class="header-section-number">2.2</span> Hypothesis tests</h2>
<p>Hypothesis tests are used to determine whether an effect is spurious or a real property of the population. A spurious effect is one that is specific to the sample we observed, and is not a real property of the population. For example, if the heights of males and female students are measured, and we observe that the sample mean of both male and females are equal, then this would be a spurious effect. We know that the population heights of males and females are substantially different. If we drew a new sample, we would likely observe something that mirrors the population reality (provided it is large enough).</p>
<p>Formally, a hypothesis test compares two competing beliefs about a population parameter, called the null and alternative hypothesis. For instance, we may wish to test whether the population heights of men is greater than women, vs.&nbsp;the heights being less than or equal to that of men.</p>
<p>We write this as follows: <span class="math inline">\(H_0\colon \mu_{men}\leq \mu_{women}\)</span> vs.&nbsp;<span class="math inline">\(H_a\colon \mu_{men}&gt; \mu_{women}\)</span>.</p>
<p>The null hypothesis is usually chosen to be one such that if we make a mistake, the error is most serious. However, it is usually clear from the context.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Intuition: hypothesis testing is like a courtroom trial">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Intuition: hypothesis testing is like a courtroom trial
</div>
</div>
<div class="callout-body-container callout-body">
<p>Think of the null hypothesis <span class="math inline">\(H_0\)</span> as “innocent until proven guilty.” We start by <em>assuming</em> <span class="math inline">\(H_0\)</span> is true (the defendant is innocent, or here, there’s no effect), and only abandon that assumption if the data provides strong enough evidence against it — just like a jury only convicts if the evidence is beyond a reasonable doubt. This is why “fail to reject <span class="math inline">\(H_0\)</span>” is not the same as “<span class="math inline">\(H_0\)</span> is proven true” — a jury verdict of “not guilty” doesn’t mean innocence was proven, only that there wasn’t enough evidence to convict. Maybe there really is no effect, or maybe there is one but our sample was too small or too noisy to detect it.</p>
</div>
</div>
<p>In general, we compute a test statistic and its distribution <strong>under the null hypothesis.</strong> Then we compute how likely it was to see the observed test statistic we saw, if the null hypothesis was true. This likelihood is given by the <strong>p-value</strong>. If it was sufficiently unlikely (in other words, the p-value is less than the threshold <span class="math inline">\(\alpha\)</span>), then we reject the null hypothesis. Otherwise, we fail to reject the null hypothesis. If we fail to reject the null hypothesis then either the null hypothesis is true, it is not true, but there was not enough data collected to show the effect.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Intuition: what a p-value actually measures">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Intuition: what a p-value actually measures
</div>
</div>
<div class="callout-body-container callout-body">
<p>A p-value answers one specific question: “<em>if</em> the null hypothesis were true, how surprising would data like ours be?” A small p-value (say, <span class="math inline">\(0.001\)</span>) means our observed test statistic would be quite rare under <span class="math inline">\(H_0\)</span> — so rare that it’s more believable that <span class="math inline">\(H_0\)</span> is simply false than that we got a fluke sample. A large p-value (say, <span class="math inline">\(0.6\)</span>) means our data looks perfectly ordinary under <span class="math inline">\(H_0\)</span> — nothing here demands an explanation beyond “no real effect.” A common misreading is to treat the p-value as “the probability <span class="math inline">\(H_0\)</span> is true” — it is <strong>not</strong> that; it’s a probability about the <em>data</em>, computed by assuming <span class="math inline">\(H_0\)</span>, not a probability about the hypothesis itself.</p>
</div>
</div>
<p>There are two types of errors we can make in a hypothesis test: Type 1 and Type 2 error. Type one error occurs when we reject the null hypothesis when it is true. Type two error occurs when we fail to reject the null hypothesis when the alternative is true.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Intuition: Type 1 vs. Type 2 error">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Intuition: Type 1 vs.&nbsp;Type 2 error
</div>
</div>
<div class="callout-body-container callout-body">
<p>Back to the courtroom: a <strong>Type 1 error</strong> is convicting an innocent person (rejecting <span class="math inline">\(H_0\)</span> when it’s actually true) — a “false alarm.” A <strong>Type 2 error</strong> is letting a guilty person go free (failing to reject <span class="math inline">\(H_0\)</span> when the alternative is actually true) — a “missed detection.” These two error types trade off against each other: making the conviction threshold stricter (smaller <span class="math inline">\(\alpha\)</span>) reduces Type 1 errors, but makes it easier for a real effect to slip through undetected (more Type 2 errors). Which error is worse depends entirely on context — for a new drug’s side effects, a false alarm (Type 1) might be much less costly than missing a real danger (Type 2); for a criminal trial, most legal systems explicitly prioritize avoiding Type 1 errors.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th><span class="math inline">\(H_0\)</span> actually true</th>
<th><span class="math inline">\(H_0\)</span> actually false</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Reject <span class="math inline">\(H_0\)</span></strong></td>
<td>Type 1 error</td>
<td>Correct</td>
</tr>
<tr class="even">
<td><strong>Fail to reject <span class="math inline">\(H_0\)</span></strong></td>
<td>Correct</td>
<td>Type 2 error</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled" title="Numerical Example 2.2: a hypothesis test and p-value by hand">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Numerical Example 2.2: a hypothesis test and p-value by hand
</div>
</div>
<div class="callout-body-container callout-body">
<p>A cereal company claims that its boxes contain, on average, <span class="math inline">\(\mu_0=500\)</span> grams of cereal. A consumer group weighs a random sample of <span class="math inline">\(n=36\)</span> boxes and finds a sample mean of <span class="math inline">\(\bar X=494\)</span> grams, with sample standard deviation <span class="math inline">\(\hat\sigma=18\)</span> grams. Test, at <span class="math inline">\(\alpha=0.05\)</span>, whether the true mean box weight differs from 500 grams.</p>
<p><em>Solution.</em> We set up the hypotheses: <span class="math display">\[H_0\colon \mu=500 \qquad \text{vs.}\qquad H_1\colon \mu\neq 500.\]</span> Since <span class="math inline">\(n=36\)</span> is reasonably large, we can treat the test statistic as approximately standard Normal under <span class="math inline">\(H_0\)</span> (equivalently, a <span class="math inline">\(t_{35}\)</span> distribution, which is very close to Normal for this many degrees of freedom): <span class="math display">\[z=\frac{\bar X-\mu_0}{\hat\sigma/\sqrt n}=\frac{494-500}{18/\sqrt{36}}=\frac{-6}{18/6}=\frac{-6}{3}=-2.\]</span> Our observed test statistic is <span class="math inline">\(-2\)</span>, meaning the sample mean is 2 standard errors below the claimed value.</p>
<p>The p-value is the probability of seeing a test statistic at least this extreme (in either direction), if <span class="math inline">\(H_0\)</span> were true: <span class="math display">\[p\text{-value}=2\times P(Z\leq -2)=2\times 0.0228=0.0456.\]</span> (Here <span class="math inline">\(0.0228\)</span> is the standard Normal lower-tail probability at <span class="math inline">\(-2\)</span>, read off a <span class="math inline">\(Z\)</span>-table or computed with <code>pnorm(-2)</code> in R.)</p>
<p>Since <span class="math inline">\(0.0456&lt;\alpha=0.05\)</span>, we reject <span class="math inline">\(H_0\)</span> — though only just, since the p-value is close to the threshold. There is evidence, though not overwhelming evidence, that the true mean box weight differs from the claimed 500 grams; in particular, since <span class="math inline">\(\bar X&lt;500\)</span>, the data suggests boxes are on average <em>underfilled</em>.</p>
<p>We can double check this with the confidence-interval method: a 95% CI for <span class="math inline">\(\mu\)</span> is <span class="math display">\[\bar X\pm 1.96\times \frac{\hat\sigma}{\sqrt n}=494\pm 1.96\times 3=494\pm 5.88=(488.12,\ 499.88).\]</span> Since the claimed value <span class="math inline">\(500\)</span> falls just outside this interval, we again reject <span class="math inline">\(H_0\colon \mu=500\)</span> — consistent with the p-value calculation above.</p>
</div>
</div>
<p>Let’s do an example.</p>
<p><strong>Exercise 2.7</strong> In a study about online dating, you are interested in determining the average age of individuals who use online dating platforms. You want to know whether the average age of online daters is significantly different from 30. You have a dataset of 40 ages of people using online dating platforms.</p>
<p>How would you answer this question?</p>
<p><span class="math display">\[H_0\colon \mu=30\qquad vs. \qquad H_1\colon \mu\neq 30.\]</span></p>
<p>First, we can explore the data:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">getwd</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>[1] "C:/Users/12RAM/OneDrive - York University/Teaching/Courses/Math 3330 Regression/Math 3330 Notes"</code></pre>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>ages<span class="ot">=</span><span class="fu">read.csv</span>(<span class="st">'C:</span><span class="sc">\\</span><span class="st">Users</span><span class="sc">\\</span><span class="st">12RAM</span><span class="sc">\\</span><span class="st">OneDrive - York University</span><span class="sc">\\</span><span class="st">Teaching</span><span class="sc">\\</span><span class="st">Courses</span><span class="sc">\\</span><span class="st">Math 3330 Regression</span><span class="sc">\\</span><span class="st">Lecture Codes</span><span class="sc">\\</span><span class="st">Data</span><span class="sc">\\</span><span class="st">dating_ages.csv'</span>)[,<span class="dv">2</span>]</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(ages,<span class="at">freq=</span>F)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><img src="Unit_1_files/figure-html/unnamed-chunk-1-1.png" class="img-fluid"></p>
<p>Now, assume that <span class="math inline">\(X_1,\ldots, X_{40}\sim \mathcal{N}(\mu,\sigma^2)\)</span>, and independent. (We can justify normality with the histogram, or we could also invoke the CLT to get normality of the sample mean (not the data itself).) Therefore, we can do a one sample <span class="math inline">\(t\)</span>-test. Recall that, under the null hypothesis, we have <span class="math inline">\(\frac{\bar X-30}{\hat\sigma/\sqrt{n}}\sim t_{n-1}\)</span>. This means that if <span class="math inline">\(\left|\frac{\bar X-30}{\hat\sigma/\sqrt{n}}\right|\geq t_{n-1,1-\alpha/2}\)</span>, then we reject the null hypothesis! Here, <span class="math inline">\(t_{n-1,1-p}\)</span> is the <span class="math inline">\((1-p)\)</span>th quantile of the <span class="math inline">\(t_{n-1}\)</span> distribution. For large <span class="math inline">\(n\)</span> and <span class="math inline">\(p=0.025\)</span>, this is roughly equal to 2.</p>
<p>Now, recall that <span class="math display">\[ H_0\colon \mu=30\qquad vs. \qquad H_1\colon \mu\neq 30 .\]</span></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the mean of the 'ages' data and assign it to xbar</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>xbar <span class="ot">=</span> <span class="fu">mean</span>(ages)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>xbar  <span class="co"># Print the mean</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>[1] 28.16378</code></pre>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the variance of the 'ages' data and assign it to ssq</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>ssq <span class="ot">=</span> <span class="fu">var</span>(ages)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>ssq  <span class="co"># Print the variance</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>[1] 1.277377</code></pre>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the length (number of observations) of the 'ages' data and assign it to n</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>n <span class="ot">=</span> <span class="fu">length</span>(ages)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>n  <span class="co"># Print the number of observations</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>[1] 40</code></pre>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Set the significance level </span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>alpha <span class="ot">=</span> <span class="fl">0.05</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="co"># print test statistic</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>ts<span class="ot">=</span>(xbar <span class="sc">-</span><span class="dv">30</span>)<span class="sc">/</span>(<span class="fu">sqrt</span>(ssq<span class="sc">/</span>n))</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(ts)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>[1] -10.27532</code></pre>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># compute p-value</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>pval<span class="ot">=</span><span class="fu">pt</span>(ts,n<span class="dv">-1</span>)<span class="sc">*</span><span class="dv">2</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>pval</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>[1] 1.179149e-12</code></pre>
<div class="callout callout-style-default callout-warning callout-titled" title="Common mistake: misreading R's scientific notation">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Common mistake: misreading R’s scientific notation
</div>
</div>
<div class="callout-body-container callout-body">
<p><code>1.179149e-12</code> is not “1.179149 times 12” — the <code>e-12</code> means “times <span class="math inline">\(10^{-12}\)</span>,” i.e., move the decimal point 12 places to the <em>left</em>. So this number is <span class="math inline">\(0.000000000001179149\)</span>, an extremely small number, not something close to 1 or 12. As a rule of thumb, <code>e-12</code>, <code>e-08</code>, etc. (negative exponent) mean “very small, close to zero,” while <code>e+08</code> or <code>e08</code> (positive exponent) would mean “very large.” Misreading this is an easy way to draw the exact opposite conclusion about how much evidence you have against <span class="math inline">\(H_0\)</span>.</p>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Perform a two-sided t-test to check if the mean of 'ages' is significantly different from 30</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="co"># t.test() is the function for performing t-tests in R</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>test <span class="ot">=</span> <span class="fu">t.test</span>(ages, <span class="at">mu =</span> <span class="dv">30</span>, <span class="at">alternative =</span> <span class="st">'two.sided'</span>)</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>test  <span class="co"># Print the test result</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>
    One Sample t-test

data:  ages
t = -10.275, df = 39, p-value = 1.179e-12
alternative hypothesis: true mean is not equal to 30
95 percent confidence interval:
 27.80232 28.52524
sample estimates:
mean of x 
 28.16378 </code></pre>
<p>We have that <span class="math inline">\(\left|\frac{\bar X-30}{\hat\sigma/\sqrt{n}}\right|=10.28\)</span>. Using R, we get that the p-value is <span class="math inline">\(1.179\times 10^{-12}\)</span>.</p>
<p>Here the p-value measures how much evidence there is against the null hypothesis. If the p-value is very small, then this constitutes strong evidence against the null hypothesis. If the p-value is small, but closer to 0.05, then there is evidence against the null. If it is larger, but still small, say 0.1, then this is weak evidence against the null hypothesis. It is not helpful to throw it away if it is above 0.05, therefore we should not just take <span class="math inline">\(\alpha=0.05\)</span>. Choosing <span class="math inline">\(\alpha\)</span> depends on how serious a type 1 error is. If it is not that serious, we can take <span class="math inline">\(\alpha\)</span> larger. If it is very serious, we can take <span class="math inline">\(\alpha\)</span> smaller.</p>
<p>In this example, there is very strong evidence against the null hypothesis.</p>
<div class="callout callout-style-default callout-warning callout-titled" title="Common mistake: statistical significance is not the same as practical importance">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Common mistake: statistical significance is not the same as practical importance
</div>
</div>
<div class="callout-body-container callout-body">
<p>A tiny p-value tells you the observed difference is unlikely to be due to chance alone — it does <strong>not</strong> tell you the difference is large or meaningful in real-world terms. Here, the sample mean age is <span class="math inline">\(28.16\)</span>, which is statistically significantly different from <span class="math inline">\(30\)</span> (p is minuscule), but a gap of under 2 years might not matter at all for whatever decision prompted the question. With a large enough sample size, even a tiny, practically irrelevant difference can produce a very small p-value, since larger <span class="math inline">\(n\)</span> makes the test statistic more sensitive to any nonzero difference. Always look at the <em>size</em> of the estimated effect (and its confidence interval) alongside the p-value, not the p-value alone.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Note also that we can use the confidence interval method with <span class="math display">\[ \bar X\pm t_{n-1,1-\alpha/2}\sqrt{\hat\sigma^2/n}.\]</span></p>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Alternative method to calculate the confidence interval</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="co"># ci will store the confidence interval values</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>ci <span class="ot">=</span> xbar <span class="sc">+</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>, <span class="dv">1</span>) <span class="sc">*</span> <span class="fu">qt</span>(<span class="dv">1</span> <span class="sc">-</span> alpha <span class="sc">/</span> <span class="dv">2</span>, n <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">*</span> <span class="fu">sqrt</span>(ssq <span class="sc">/</span> n)</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>ci  <span class="co"># Print the confidence interval</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>[1] 27.80232 28.52524</code></pre>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Moving beyond the one-sample testing problem, we might be interested in other population parameters, say <span class="math inline">\(\theta\in \Theta\)</span>. Think Lecture 1: <span class="math inline">\({\textrm{E}}\left[Y|X\right]=\beta_0+X\beta_1\)</span>, we might want to estimate <span class="math inline">\({\textrm{E}}\left[Y|X\right]\)</span>, which amounts to <span class="math inline">\(\beta_0,\beta_1\in \mathbb{R}\)</span>! In general, we may estimate <span class="math inline">\(\theta\)</span> by <span class="math inline">\(\hat\theta\)</span>. Then we may compute the variance and distribution of <span class="math inline">\(\hat\theta\)</span>. From there, we can make confidence intervals and conduct hypothesis tests etc.</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Intuition: two-sample tests just apply the same idea to a difference">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Intuition: two-sample tests just apply the same idea to a difference
</div>
</div>
<div class="callout-body-container callout-body">
<p>Nothing new is happening conceptually here — we’re still doing the same “assume <span class="math inline">\(H_0\)</span>, see how surprising the data is” procedure. The only change is that our parameter of interest, <span class="math inline">\(\Delta=\mu_1-\mu_2\)</span>, is now a <em>difference</em> of two means instead of a single mean. Once we know how to find the distribution of <span class="math inline">\(\hat\Delta=\bar X-\bar Y\)</span> (the natural estimator of <span class="math inline">\(\Delta\)</span>), everything else — the test statistic, the p-value, the confidence interval — follows exactly the same recipe as the one-sample case above.</p>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled" title="Numerical Example 2.3: a two-sample t-test by hand">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Numerical Example 2.3: a two-sample t-test by hand
</div>
</div>
<div class="callout-body-container callout-body">
<p>A teacher wants to know whether two different study methods lead to different average test scores. Method A is used by <span class="math inline">\(n_1=10\)</span> students, giving sample mean <span class="math inline">\(\bar X=78\)</span> and sample variance <span class="math inline">\(\hat\sigma_1^2=25\)</span>. Method B is used by <span class="math inline">\(n_2=12\)</span> students, giving sample mean <span class="math inline">\(\bar Y=82\)</span> and sample variance <span class="math inline">\(\hat\sigma_2^2=36\)</span>. Assume both populations are Normal with a common (but unknown) variance <span class="math inline">\(\sigma^2\)</span>. Test <span class="math inline">\(H_0\colon \Delta=\mu_1-\mu_2=0\)</span> vs.&nbsp;<span class="math inline">\(H_1\colon \Delta\neq 0\)</span> at <span class="math inline">\(\alpha=0.05\)</span>.</p>
<p><em>Solution.</em> First we pool the two sample variances into a single estimate of the common <span class="math inline">\(\sigma^2\)</span>, weighting each by its degrees of freedom: <span class="math display">\[\hat\sigma_p^2=\frac{(n_1-1)\hat\sigma_1^2+(n_2-1)\hat\sigma_2^2}{n_1+n_2-2}=\frac{(9)(25)+(11)(36)}{10+12-2}=\frac{225+396}{20}=\frac{621}{20}=31.05.\]</span></p>
<p>Next, the test statistic is <span class="math display">\[t=\frac{\bar X-\bar Y}{\hat\sigma_p\sqrt{1/n_1+1/n_2}}=\frac{78-82}{\sqrt{31.05}\sqrt{1/10+1/12}}=\frac{-4}{5.572\times\sqrt{0.1833}}=\frac{-4}{5.572\times 0.4282}=\frac{-4}{2.386}\approx -1.677.\]</span></p>
<p>This statistic follows a <span class="math inline">\(t_{n_1+n_2-2}=t_{20}\)</span> distribution under <span class="math inline">\(H_0\)</span>. The critical value for a two-sided test at <span class="math inline">\(\alpha=0.05\)</span> with 20 degrees of freedom is <span class="math inline">\(t_{20,0.975}\approx 2.086\)</span>. Since <span class="math inline">\(|{-1.677}|=1.677&lt;2.086\)</span>, we <strong>fail to reject</strong> <span class="math inline">\(H_0\)</span>: this sample does not provide strong enough evidence, at the 5% level, that the two study methods lead to different average scores (even though the observed sample means, 78 vs.&nbsp;82, do differ numerically — with only 10 and 12 students per group, that gap is well within what we’d expect from sampling variability alone).</p>
<p>Equivalently, using the confidence-interval method, a 95% CI for <span class="math inline">\(\Delta=\mu_1-\mu_2\)</span> is <span class="math display">\[(\bar X-\bar Y)\pm t_{20,0.975}\,\hat\sigma_p\sqrt{1/n_1+1/n_2}=-4\pm 2.086\times 2.386=-4\pm 4.977=(-8.98,\ 0.98).\]</span> Since this interval contains 0, we again fail to reject <span class="math inline">\(H_0\colon \Delta=0\)</span>.</p>
</div>
</div>
<p>Let’s do another example:</p>
<p><strong>Exercise 2.8</strong> In a study about online dating, you are interested in determining if the average age of those who identify as men who use online dating platforms differs from those who identify as women. You have a dataset of 20 ages of each group using online dating platforms.</p>
<p>What is the population parameter of interest here? It is <span class="math inline">\(\Delta=\mu_{1}-\mu_2\)</span>, the difference in means between the two populations. Now, suppose that <span class="math inline">\(X_1,\ldots, X_{20}\sim \mathcal{N}(\mu_1,\sigma^2)\)</span> and <span class="math inline">\(Y_1,\ldots, Y_{20}\sim \mathcal{N}(\mu_2,\sigma^2)\)</span>, and are mutually independent. (We could also invoke the CLT instead of assuming normality.) We can estimate those parameters with <strong>estimates.</strong> For instance, <span class="math inline">\(\bar X,\ \bar Y\)</span>, <span class="math display">\[\hat\sigma^2=\frac{(n_1-1)\hat\sigma_1^2+(n_2-1)\hat\sigma_2^2}{n_1+n_2-2}.\]</span></p>
<p><strong>Exercise 2.9</strong> Suppose that <span class="math inline">\(X_1,\ldots, X_{20}\sim \mathcal{N}(\mu_1,\sigma^2)\)</span> and <span class="math inline">\(Y_1,\ldots, Y_{20}\sim \mathcal{N}(\mu_2,\sigma^2)\)</span>, and are mutually independent. Compute <span class="math inline">\({\textrm{Var}}\left[\bar X-\bar Y\right]\)</span>.</p>
<p><em>Solution 2.3</em>. Using independence of <span class="math inline">\(\bar X\)</span> and <span class="math inline">\(\bar Y\)</span> and the result of the <a href="#exr-6">Exercise&nbsp;2.6</a> , we have that <span class="math display">\[{\textrm{Var}}\left[\bar X-\bar Y\right]={\textrm{Var}}\left[\bar X\right]+{\textrm{Var}}\left[\bar Y\right]=\sigma_1^2/n_1+\sigma_1^2/n_2.\]</span></p>
<p>First, we write down the null and alternative hypothesis: <span class="math display">\[H_0\colon \Delta=0\qquad vs.. \qquad H_1\colon \Delta\neq 0.\]</span> Here, we can do a two sample <span class="math inline">\(t\)</span>-test.</p>
<p>Recall that the pooled variance is given by: <span class="math display">\[\hat\sigma_p^2=\frac{(n_1-1)\hat\sigma_1^2+(n_2-1)\hat\sigma_2}{(n_1+n_2-2)}\]</span> We previously said that a multiple of a one sample standard deviation follows a Chi-squared distribution. It follows that <span class="math inline">\((n_1-1)\hat\sigma_1^2/\sigma^2\sim \chi^2_{n_1-1}\)</span> and <span class="math inline">\((n_2-1)\hat\sigma_2^2/\sigma^2\sim \chi^2_{n_2-1}\)</span>. Using the theory from <a href="#Useful-properties-of%20normal-and-related-random-variables">here</a>, specifically, <span class="math inline">\((n_1-1)\hat\sigma_1^2/\sigma^2+(n_2-1)\hat\sigma_2^2/\sigma^2\)</span> is a sum of independent Chi-squared random variables, and so we have <span class="math inline">\((n_1-1)\hat\sigma_1^2/\sigma^2+(n_2-1)\hat\sigma_2^2/\sigma^2\sim \chi^2_{n_1+n_2-2}\)</span>.</p>
<p>Again, using the theory from <a href="#Useful-properties-of%20normal-and-related-random-variables">here</a>, under the null hypothesis, we have that <span class="math display">\[\frac{\bar X-\bar Y}{\hat\sigma_p\sqrt{1/n_1+1/n_2}}=\frac{(\bar X-\bar Y)/\sigma\sqrt{1/n_1+1/n_2}}{\hat\sigma_p/\sigma}\sim t_{n_1+n_2-2}.\]</span></p>
<p>This follows from 3 facts, first, letting <span class="math inline">\(Z=(\bar X-\bar Y)/\sqrt{{\textrm{Var}}\left[\bar X-\bar Y\right]}\)</span>, note that <span class="math inline">\(Z\sim \mathcal{N}(0,1)\)</span>. We have that <span class="math display">\[Z=(\bar X-\bar Y)/\sqrt{{\textrm{Var}}\left[\bar X-\bar Y\right]}=(\bar X-\bar Y)/\sigma\sqrt{1/n_1+1/n_2}.\]</span></p>
<p>Next, we said earlier that <span class="math inline">\(\bar X\)</span> is independent of <span class="math inline">\(\hat\sigma_1\)</span> and <span class="math inline">\(\bar Y\)</span> is independent of <span class="math inline">\(\hat\sigma_2\)</span>. Now, recall that if two random variables are independent, then any function of them is also independent. In other words, if <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> are independent, then for real functions <span class="math inline">\(f\)</span> and <span class="math inline">\(g\)</span>, we have that <span class="math inline">\(g(X)\)</span> is independent of <span class="math inline">\(f(Y)\)</span>. It follows that <span class="math inline">\(\bar X\)</span> is independent of <span class="math inline">\(\hat\sigma_2\)</span> and <span class="math inline">\(\bar Y\)</span> is independent of <span class="math inline">\(\hat\sigma_1\)</span>. It follows that <span class="math inline">\(\bar X-\bar Y\)</span> is independent of <span class="math inline">\(\hat\sigma_p\)</span>. Then, <span class="math display">\[\frac{(\bar X-\bar Y)/\sigma\sqrt{1/n_1+1/n_2}}{\hat\sigma_p/\sigma}\]</span> is a ratio of a standard normal random variable and the square root of a Chi-squared random variable, divided by its degrees of freedom. Further, the numerator and denominator are independent. Therefore, the above quantity follows a <span class="math inline">\(t\)</span> distribution with <span class="math inline">\(n_1+n_2-2\)</span> degrees of freedom.</p>
<p>This means that if <span class="math inline">\(\left|\frac{\bar X-\bar Y}{\hat\sigma_p\sqrt{1/n_1+1/n_2}}\right|\geq t_{n_1+n_2-2,1-\alpha/2}\)</span>, then we reject the null hypothesis.</p>
<p>Let’s execute the test in R:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Normally, I will give you a dataset. Here I generate the data</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">440</span>) </span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>female_ages<span class="ot">=</span><span class="fu">rnorm</span>(<span class="dv">20</span>,<span class="dv">28</span>,<span class="dv">4</span>)</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>male_ages<span class="ot">=</span><span class="fu">rnorm</span>(<span class="dv">20</span>,<span class="dv">32</span>,<span class="dv">4</span>)</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Check for equal variance</span></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a><span class="fu">var</span>(female_ages)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>[1] 15.72805</code></pre>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">var</span>(male_ages)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>[1] 26.22371</code></pre>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Putting the data in a dataframe</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cbind</span>(<span class="st">"Age"</span><span class="ot">=</span><span class="fu">c</span>(female_ages,male_ages),<span class="st">"Gender"</span><span class="ot">=</span><span class="fu">rep</span>(<span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>),<span class="at">each=</span><span class="dv">20</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>           Age Gender
 [1,] 37.19809      0
 [2,] 20.69693      0
 [3,] 27.80284      0
 [4,] 27.69463      0
 [5,] 29.53143      0
 [6,] 29.46190      0
 [7,] 30.41164      0
 [8,] 33.27790      0
 [9,] 22.65974      0
[10,] 30.73540      0
[11,] 34.08564      0
[12,] 27.58077      0
[13,] 23.26108      0
[14,] 30.94523      0
[15,] 31.52404      0
[16,] 29.13246      0
[17,] 26.95470      0
[18,] 24.80749      0
[19,] 28.60051      0
[20,] 26.76294      0
[21,] 25.94775      1
[22,] 40.16080      1
[23,] 25.58905      1
[24,] 32.16780      1
[25,] 29.87934      1
[26,] 35.46593      1
[27,] 35.71651      1
[28,] 37.76510      1
[29,] 27.23068      1
[30,] 33.41994      1
[31,] 40.43822      1
[32,] 31.04841      1
[33,] 32.66165      1
[34,] 38.28678      1
[35,] 34.72411      1
[36,] 39.57994      1
[37,] 26.85585      1
[38,] 31.87533      1
[39,] 23.71793      1
[40,] 30.54803      1</code></pre>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>df<span class="ot">=</span><span class="fu">data.frame</span>(<span class="fu">cbind</span>(<span class="st">"Age"</span><span class="ot">=</span><span class="fu">c</span>(female_ages,male_ages),<span class="st">"Gender"</span><span class="ot">=</span><span class="fu">rep</span>(<span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>),<span class="at">each=</span><span class="dv">20</span>)))</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="co">#exploring the data</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a><span class="co">#hist(x) creates a histogram of the vector x</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(df<span class="sc">$</span>Age[df<span class="sc">$</span>Gender<span class="sc">==</span><span class="dv">0</span>])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><img src="Unit_1_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid"></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(df<span class="sc">$</span>Age[df<span class="sc">$</span>Gender<span class="sc">==</span><span class="dv">1</span>])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><img src="Unit_1_files/figure-html/unnamed-chunk-4-2.png" class="img-fluid"></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co">#boxplot creates boxplots of Age against gender</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(Age<span class="sc">~</span>Gender, df)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><img src="Unit_1_files/figure-html/unnamed-chunk-4-3.png" class="img-fluid"></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>test<span class="ot">=</span><span class="fu">t.test</span>(Age<span class="sc">~</span>Gender,<span class="at">data=</span>df,<span class="at">var.equal=</span><span class="cn">TRUE</span>)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>test</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>
    Two Sample t-test

data:  Age by Gender
t = -2.7603, df = 38, p-value = 0.008841
alternative hypothesis: true difference in means between group 0 and group 1 is not equal to 0
95 percent confidence interval:
 -6.929630 -1.065749
sample estimates:
mean in group 0 mean in group 1 
       28.65627        32.65396 </code></pre>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Interpret the P value, and CI, what are we going to say to a stakeholder?</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a><span class="co">#e.g.</span></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>test<span class="sc">$</span>estimate</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>mean in group 0 mean in group 1 
       28.65627        32.65396 </code></pre>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Note also that we can use the confidence interval method, meaning that if if 0 is in the interval: <span class="math display">\[ \hat\Delta\pm t_{n_1+n_2-2,1-\alpha/2}\hat\sigma_p\sqrt{1/n_1+1/n_2},\]</span> then we fail to reject the null hypothesis.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Key takeaways before moving on">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Key takeaways before moving on
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>A confidence interval quantifies sampling uncertainty in an estimate; the randomness lives in the <em>interval</em>, not in the fixed, unknown population parameter.</li>
<li>A hypothesis test starts by assuming <span class="math inline">\(H_0\)</span> is true, then asks how surprising the observed data would be under that assumption — that surprise level is the p-value.</li>
<li>A small p-value is evidence <em>against</em> <span class="math inline">\(H_0\)</span>, not a probability that <span class="math inline">\(H_0\)</span> is true.</li>
<li>Type 1 error (false alarm: rejecting a true <span class="math inline">\(H_0\)</span>) and Type 2 error (missed detection: failing to reject a false <span class="math inline">\(H_0\)</span>) trade off against each other, and which one matters more depends on context.</li>
<li>Two-sample tests (comparing <span class="math inline">\(\mu_1\)</span> vs.&nbsp;<span class="math inline">\(\mu_2\)</span>) use exactly the same logic as one-sample tests, just applied to the difference <span class="math inline">\(\Delta=\mu_1-\mu_2\)</span>.</li>
</ul>
</div>
</div>
<p><strong>Exercise 2.10</strong> IBM Human Resources (HR) department is evaluating job applicants from York University.</p>
<p>They are interested to know if the 2020 ITEC graduating class has an average GPA higher than 6 (i.e.&nbsp;average GPA higher than ``B’’). They collected the GPA of 25 ITEC students graduated in 2020.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>4.92</th>
<th>4.79</th>
<th>6.76</th>
<th>5.64</th>
<th>6.12</th>
<th>7.37</th>
<th>6.45</th>
<th>6.31</th>
<th>6.68</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>6.30</td>
<td>4.91</td>
<td>6.95</td>
<td>5.87</td>
<td>6.18</td>
<td>6.60</td>
<td>6.71</td>
<td>6.69</td>
<td>5.62</td>
</tr>
<tr class="even">
<td>6.40</td>
<td>5.51</td>
<td>6.44</td>
<td>6.13</td>
<td>8.55</td>
<td>7.94</td>
<td>4.78</td>
<td>-</td>
<td>-</td>
</tr>
</tbody>
</table>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>Use chatGPT to convert the above table to an R vector, so you don’t have to waste time!</p>
</div>
</div>
<ul>
<li>For the one sample testing problem, i.e., you have a sample of <span class="math inline">\(n\)</span> normal random variables, with unknown mean and variance and you want to test whether <span class="math inline">\(H_0\colon \mu=0\)</span> vs.&nbsp;<span class="math inline">\(H_0\colon \mu\neq 0\)</span>, show that <span class="math inline">\(\frac{\bar X}{\hat\sigma/\sqrt{n}}\sim t_{n-1}\)</span> under the null hypothesis, assuming the observations are normally distributed.</li>
<li>What is the distribution of each of the following: <span class="math inline">\(\bar X,\hat\sigma^2\)</span> (sample mean and sample variance) under the assumption of normal data with unknown mean and variance?</li>
</ul>
<p>Compare and contrast the following concepts. That is, define them and explain the difference between them.</p>
<ul>
<li>Sample vs.&nbsp;Population</li>
<li>Observation vs.&nbsp;Random variable</li>
<li>Statistic vs.&nbsp;Parameter</li>
<li>Estimate vs.&nbsp;Estimator</li>
</ul>
</section>
<section id="check-your-understanding" class="level2" data-number="2.3">
<h2 data-number="2.3" data-anchor-id="check-your-understanding"><span class="header-section-number">2.3</span> Check Your Understanding</h2>
<style>
details.qa-answer { margin: 0 0 1.25em 0; border-left: 3px solid #d6eaf8; padding-left: 0.75em; }
details.qa-answer > summary { cursor: pointer; color: #2e86c1; font-weight: 600; }
details.qa-answer > summary::marker { color: #2e86c1; }
details.qa-answer[open] > summary { margin-bottom: 0.5em; }
details.qa-answer p { margin: 0; }
</style>
<p>Review your material and complete the above exercises before continuing to the next section. The questions below are a quick self-check on the material from this page — try each one, then click <strong>Show answer</strong> to check yourself.</p>
<p><strong>Question 1.</strong> A 90% confidence interval for the average commute time of employees at a company is <span class="math inline">\((22,28)\)</span> minutes. Which of the following is a correct interpretation? (a) There’s a 90% chance the true average commute time is between 22 and 28 minutes. (b) If we repeated this sampling procedure many times, about 90% of the resulting intervals would contain the true average commute time.</p>
<details class="qa-answer">
<summary>
Show answer
</summary>
<p>
(b). The true average commute time is a fixed (though unknown) number — it either is or isn’t in <span class="math inline">\((22,28)\)</span>, so it doesn’t make sense to assign it a probability. It’s the interval’s endpoints that are random, varying from sample to sample, which is exactly what statement (b) describes.
</p>
</details>
<p><strong>Question 2.</strong> A researcher tests <span class="math inline">\(H_0\colon \mu=0\)</span> vs.&nbsp;<span class="math inline">\(H_1\colon \mu\neq0\)</span> and gets a p-value of <span class="math inline">\(0.03\)</span>. Using <span class="math inline">\(\alpha=0.05\)</span>, what do they conclude? What does the p-value of <span class="math inline">\(0.03\)</span> actually represent?</p>
<details class="qa-answer">
<summary>
Show answer
</summary>
<p>
Since <span class="math inline">\(0.03&lt;0.05\)</span>, they reject <span class="math inline">\(H_0\)</span>. The p-value of <span class="math inline">\(0.03\)</span> means: if <span class="math inline">\(H_0\)</span> were actually true (true mean is 0), there would only be a 3% chance of observing a test statistic at least as extreme as the one actually observed. That’s unlikely enough to conclude <span class="math inline">\(H_0\)</span> is probably false — it is not the probability that <span class="math inline">\(H_0\)</span> itself is true.
</p>
</details>
<p><strong>Question 3.</strong> A factory’s quality control test has <span class="math inline">\(H_0\colon\)</span> “the product is safe” vs.&nbsp;<span class="math inline">\(H_1\colon\)</span> “the product is defective.” Which type of error (Type 1 or Type 2) is more serious here, and why?</p>
<details class="qa-answer">
<summary>
Show answer
</summary>
<p>
Type 2 error (failing to reject <span class="math inline">\(H_0\)</span> — i.e., concluding the product is safe — when it’s actually defective) is generally far more serious here, since it means a genuinely dangerous product reaches consumers. A Type 1 error (flagging a safe product as defective) is costly but not dangerous. In practice this would push a company toward a testing procedure that is more sensitive to detecting defects, even at the cost of more false alarms.
</p>
</details>
<p><strong>Question 4.</strong> True or False: failing to reject <span class="math inline">\(H_0\)</span> proves that <span class="math inline">\(H_0\)</span> is true. Explain.</p>
<details class="qa-answer">
<summary>
Show answer
</summary>
<p>
False. Failing to reject <span class="math inline">\(H_0\)</span> only means the data didn’t provide strong enough evidence against it — it could be that <span class="math inline">\(H_0\)</span> really is true, or that it’s false but the effect was too small or the sample too small/noisy to detect it. It is never proof that <span class="math inline">\(H_0\)</span> is true, the same way a “not guilty” verdict doesn’t prove innocence.
</p>
</details>
<p><strong>Question 5.</strong> In the two-sample dating-age example on this page, why can we use a <span class="math inline">\(t\)</span>-distribution (rather than, say, a Normal distribution) for the test statistic <span class="math inline">\(\frac{\bar X-\bar Y}{\hat\sigma_p\sqrt{1/n_1+1/n_2}}\)</span>?</p>
<details class="qa-answer">
<summary>
Show answer
</summary>
<p>
Because the true variance <span class="math inline">\(\sigma^2\)</span> is unknown and had to be estimated (via the pooled variance <span class="math inline">\(\hat\sigma_p^2\)</span>) from the data. Dividing a standard Normal by an independent, <em>estimated</em> standard deviation is exactly the situation that produces a <span class="math inline">\(t\)</span>-distribution rather than a Normal — the extra uncertainty from estimating <span class="math inline">\(\sigma^2\)</span> widens the tails compared to a Normal.
</p>
</details>
<p><strong>Question 6.</strong> A 95% confidence interval for <span class="math inline">\(\mu\)</span> turns out to be <span class="math inline">\((1.2, 4.8)\)</span>. Without redoing any calculations, what can you immediately conclude about a two-sided test of <span class="math inline">\(H_0\colon \mu=0\)</span> vs.&nbsp;<span class="math inline">\(H_1\colon \mu\neq 0\)</span> at <span class="math inline">\(\alpha=0.05\)</span>?</p>
<details class="qa-answer">
<summary>
Show answer
</summary>
<p>
We would reject <span class="math inline">\(H_0\)</span>. The confidence-interval method mentioned on this page says: fail to reject <span class="math inline">\(H_0\colon\mu=\mu_0\)</span> at level <span class="math inline">\(\alpha\)</span> exactly when <span class="math inline">\(\mu_0\)</span> falls inside the <span class="math inline">\((1-\alpha)100\%\)</span> confidence interval. Since <span class="math inline">\(0\)</span> is not inside <span class="math inline">\((1.2,4.8)\)</span>, the test rejects <span class="math inline">\(H_0\colon\mu=0\)</span> — no need to recompute the test statistic or p-value from scratch.
</p>
</details>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./Unit_1_1.html" class="pagination-link" aria-label="Review of random variables">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Review of random variables</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./Unit_1_3.html" class="pagination-link" aria-label="Review of matrices and linear algebra">
        <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Review of matrices and linear algebra</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>